// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NursingHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperationLog", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("affected_entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("device_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("operation_description")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("operation_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime>("operation_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("operation_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("staff_id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("log_id");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("SystemAnnouncements", b =>
                {
                    b.Property<int>("announcement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("announcement_id"));

                    b.Property<string>("announcement_content")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("announcement_date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("announcement_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("audience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("created_by")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("read_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("announcement_id");

                    b.ToTable("SystemAnnouncements");
                });

            modelBuilder.Entity("VisitorRegistration", b =>
                {
                    b.Property<int>("visitor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("visitor_id"));

                    b.Property<string>("approval_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("elderly_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("family_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("relationship_to_elderly")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("visit_reason")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<DateTime>("visit_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("visit_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("visitor_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("visitor_id");

                    b.ToTable("VisitorRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
